### ISSUE TITLE
list_filter_header does not exist

### ISSUE THREAD

**Issue by gchabert** [ibex-team/template-ibex-plugin-cmake#1]
Cette ligne là dans src/CMakeLists.txt:

``list_filter_header (HDR ${SRC}) # Ibex should have installed this function``

ne produit rien apparemment (pas d'installation des headers).
Je ne trouve pas de fonction ``list_filter_header`` dans ibex.

**Comment by cyrilbouvier** [comment]
La fonction `list_filter_header` est definie dans le fichier `cmake.utils/ibex-config-utils.cmake` du répo ibex-lib.

Son but est de filtrer uniquement les fichiers headers (.h et .inl) qui doivent être installés. Après l'appel, la variable HDR contient la liste des fichiers headers. Ensuite il faut les installer avec une commande du type:

```
install (FILES ${HDR} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ibex-myplugin)
```

**Comment by gchabert** [comment]
Ok, pourtant les includes ne sont pas installés. Lorsque j'affiche 
``message("headers" ${HDR})``
après l'appel à `list_filter_header (HDR ${SRC})`, il n'y a rien dans HDR visiblement.

**Comment by cyrilbouvier** [comment]
Quel est le fichier CMakeLists.txt complet ? Quel est la sortie de la commande cmake ?
Quel est le contenu de `SRC` ?

**Comment by gchabert** [comment]
J'ai pris l'exemple du plugin ibex-param-estim. Le fichier CMakeLists.txt est donc [celui-ci](https://github.com/ibex-team/ibex-param-estim/blob/master/src/CMakeLists.txt). Dans la version actuellement sous github, j'ai rajouté à la main les headers dans HDR, donc ça fonctionne. Il faut donc retirer cela pour observer le problème.

La sortie de cmake est la suivante. Il y a bien un warning, mais sans rapport avec le problème:
```
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Ibex version 2.8.6
-- Running on system Linux-5.3.0-61-generic with processor x86_64
-- Using CMake 3.10.2
-- C++ compiler: GNU 7.5.0
-- Will build static libraries
-- Setting build type to 'Release' as none was specified.
headers
CMake Warning (dev) at /home/gilles/ibex/share/ibex/cmake/ibex-config-utils.cmake:164 (add_subdirectory):
  The source directory

    /home/gilles/ibex-plugins/ibex-param-estim/tests

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:24 (add_make_target_for_ctest)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/gilles/ibex-plugins/ibex-param-estim/build
```

La sortie de `make` :
```
Scanning dependencies of target ibex-param-estim
[ 18%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/ibex_QInter2.cpp.o
[ 18%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/ibex_QInter_coreF.cpp.o
[ 27%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/ibex_QInter_projF.cpp.o
[ 36%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/ibex_QInterEx_Cliquer.cpp.o
[ 45%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/ibex_KCoreGraph.cpp.o
[ 54%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/cliquer/graph.cpp.o
[ 63%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/ibex_CtcQInter2.cpp.o
[ 72%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/cliquer/cliquer.cpp.o
[ 81%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/cliquer/cl.cpp.o
[ 90%] Building CXX object src/CMakeFiles/ibex-param-estim.dir/cliquer/reorder.cpp.o
[100%] Linking CXX static library libibex-param-estim.a
[100%] Built target ibex-param-estim
```
et de `make install` :

```
[100%] Built target ibex-param-estim
Install the project...
-- Install configuration: "Release"
-- Installing: /home/gilles/ibex-plugins/ibex-param-estim/lib/libibex-param-estim.a

```

**Comment by cyrilbouvier** [comment]
Il y avait un bug dans la fonction, je l'ai corrigé, cf commit ibex-team/ibex-lib@aba42969e7
Il faut que tu réinstalles ibex pour que le nouveau fichier soit pris en compte par le plugin.

**Comment by gchabert** [comment]
Cyril, j'ai refait le test from scratch (git pull, compil et install ibex puis compil et install du plugin) et j'ai toujours le même problème. Es-tu sûr d'avoir fixé le bug?

**Comment by cyrilbouvier** [comment]
Oups désolé, j'avais testé plusieurs versions mais j'ai pas comité la bonne. Je viens de commiter la bonne version: ibex-team/ibex-lib@2ee84b16

**Comment by gchabert** [comment]
Cette fois c'est bon, merci.
