### ISSUE TITLE
<lower-case-name>-config.cmake is not generated

### ISSUE THREAD

**Issue by Rapha811** [ibex-team/template-ibex-plugin-cmake#2]
I think there is some code in the `CMakeLists.txt` missing to generate the `<lower-case-name>-config.cmake` file. 

This file is required to call `find_package` which can be used to find the built plugin from another project.

**Comment by cyrilbouvier** [comment]
This is in my TODO list to write the cmake function for this.
But it is not easy as they are lots of cases to take into account. For now, you will have to write/generate it by hand.

**Comment by cyrilbouvier** [comment]
There is now an example on the repo on how to generate it the cmake config file.
