### ISSUE TITLE
Unknown CMake command "ibex_list_filter_header".

### ISSUE THREAD

**Issue by Jordan08** [ibex-team/template-ibex-plugin-cmake#3]
Bonjour, 
j'ai essayé de reprendre ce projet pour faire le cmake du plugging pour AMPL.
Mais j'ai cette erreur dans ce projet même 

CMake Error at src/CMakeLists.txt:17 (ibex_list_filter_header):
  Unknown CMake command "ibex_list_filter_header".
-- Configuring incomplete, errors occurred!

voici ma commande cmake:
cmake .. -DCMAKE_INSTALL_PREFIX=../../OUT -DCMAKE_PREFIX_PATH=/home/XXXXXXXX/IBEX/GIT_IBEX/OUT/ 

Merci d'avance

**Comment by cyrilbouvier** [comment]
Il faut utiliser la version d'Ibex la plus récente possible (2.8.9.1).
Qu'affiche CMake sur la ligne `Found Ibex version ...` ?

**Comment by Jordan08** [comment]
J'ai pris la version de la branch master , cad 2.8.8
Je vais essayer avec celle de la branch develop
merci

**Comment by Jordan08** [comment]
Merci le cmake marche.
Mais j'ai un problème de lien avec la librairie externe ASL.
Je n'arrive pas a lancer l'installation "automatique" avec le cmake du projet (tout est dans le zip dans le ibex-ampl/3rd )

et j'ai un problème dans les liens

`  bash:   cmake .. -DCMAKE_INSTALL_PREFIX=../../OUT3 -DCMAKE_PREFIX_PATH=/home/XXXXX/IBEX/GIT_IBEX/OUT3/ -DASL_DIR='/home/XXXXX/IBEX/GIT_ASL/OUT/'
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Ibex version 2.8.9.1
-- Running on system Linux-5.8.0-36-generic with processor x86_64
-- Using CMake 3.16.3
-- C++ compiler: GNU 9.3.0
-- Will build static libraries
-- Setting build type to 'Release' as none was specified.
-- Ibex was compiled with interval library Filib 3.0.2.2
-- Ibex was compiled without any Linear Programming library
-- Looking for asl/asl.h
-- Looking for asl/asl.h -- found at /home/XXXXX/IBEX/GIT_ASL/OUT/include
-- Looking for asl
-- Looking for asl -- found at /home/XXXXX/IBEX/GIT_ASL/OUT/lib/libasl.a
-- Could NOT find CppUnit (missing: CPPUNIT_LIBRARY CPPUNIT_INC_DIR) 
-- Will not run tests, required cppunit library was not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/XXXXX/IBEX/GIT_AMPL/ibex-ampl/build

bash:~/XXXXX/IBEX/GIT_AMPL/ibex-ampl/build$ make
Scanning dependencies of target ibex-ampl
[ 25%] Building CXX object src/CMakeFiles/ibex-ampl.dir/system/ibex_AmplInterface.cpp.o
/home/XXXXX/IBEX/GIT_AMPL/ibex-ampl/src/system/ibex_AmplInterface.cpp:18:10: fatal error: asl/asl.h: Aucun fichier ou dossier de ce type
   18 | #include "asl/asl.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/ibex-ampl.dir/build.make:63 : src/CMakeFiles/ibex-ampl.dir/system/ibex_AmplInterface.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:966 : src/CMakeFiles/ibex-ampl.dir/all] Erreur 2
make: *** [Makefile:141 : all] Erreur 2`

**Comment by Jordan08** [comment]
le depot ASL est là:
https://github.com/ampl/asl

**Comment by cyrilbouvier** [comment]
Sans voir le code des scripts CMake c'est difficile de dire ce qu'il se passe.
D'après l'output, CMake a trouvé le header et la bibliothèque
```
-- Looking for asl/asl.h
-- Looking for asl/asl.h -- found at /home/XXXXX/IBEX/GIT_ASL/OUT/include
-- Looking for asl
-- Looking for asl -- found at /home/XXXXX/IBEX/GIT_ASL/OUT/lib/libasl.a
```

**Comment by Jordan08** [comment]
Tout est dans la branch develop du depot ibex-ampl.
J'y rouvre une issue
a+
